# Generated by Django 5.0.6 on 2024-06-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyflansapp', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
