# Generated by Django 5.0.6 on 2024-06-12 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyflansapp', '0003_flan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
        ),
    ]
